name: planning
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  collection: ^1.17.0
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.5
  device_info_plus: ^4.1.3
  drag_and_drop_lists: ^0.3.3
  equatable: ^2.0.5
  excel: ^2.0.1
  external_path: ^1.0.3
  file_picker: ^5.2.5
  fl_country_code_picker: ^0.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  flutter_speed_dial: ^6.2.0
  flutter_timezone: ^1.0.4
  font_awesome_flutter: ^10.4.0
  hive_flutter: ^1.1.0
  html_editor_enhanced: ^2.5.1
  http: ^0.13.5
  material_segmented_control: ^4.1.1
  mime_type: ^1.0.0
  multi_select_flutter: ^4.1.3
  open_filex: ^4.3.2
  passwordfield: ^0.1.0
  path_provider: ^2.0.12
  pdfx: ^2.3.0
  permission_handler: ^10.2.0
  pointer_interceptor: ^0.9.3+4
  qr_code_scanner: ^1.0.1
  responsive_grid: ^2.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.17
  sticky_headers: ^0.3.0+2
  syncfusion_flutter_calendar: ^20.4.50
  syncfusion_flutter_core: ^20.4.50
  syncfusion_flutter_pdf: ^20.4.50
  syncfusion_flutter_pdfviewer: ^20.4.50
  syncfusion_localizations: ^20.4.50
  table_calendar: ^3.0.8
  table_sticky_headers: ^2.0.5
  timezone: ^0.9.1
  universal_html: ^2.0.9
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.17


flutter_icons:
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: BubbleBee
      fonts:
        - asset: fonts/BubbleBee.ttf

    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf

    - family: Dancing
      fonts:
        - asset: fonts/DancingScript-Medium.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat.ttf

    - family: Montserrat-Medium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

    - family: Delberg
      fonts:
        - asset: fonts/Delberg.ttf

    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
