name: planning
description: Planificación de Eventos.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  http:
  rxdart: ^0.27.1
  excel:
  responsive_builder: ^0.4.1
  contacts_service:
  permission_handler: ^8.1.4+2
  multi_select_item:
  url_launcher: ^6.0.12
  open_file: ^3.2.1
  flutter_login:
  material_segmented_control:
  flutter_bloc: ^7.3.3
  equatable:
  shared_preferences: ^2.0.5
  native_pdf_view: ^4.0.1
  syncfusion_flutter_pdf: ^19.1.67-beta
  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^2.0.0
  qr_code_scanner: ^0.6.1
  path_provider: ^2.0.5
  #fab_circular_menu: ^1.0.2
  flutter_speed_dial: ^4.2.0
  html_editor_enhanced: 2.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  # sticky_headers
  sticky_headers: ^0.2.0
  passwordfield: ^0.0.82
  table_sticky_headers: ^2.0.0
  table_calendar: ^3.0.3
  multi_select_flutter: ^4.0.0
  file_picker: ^4.3.1
  syncfusion_flutter_pdfviewer: ^19.3.54-beta
  mime_type: ^1.0.0
  screenshot: ^1.2.3
  pdf: ^3.6.0
  webview_flutter: ^2.1.1
  pointer_interceptor: ^0.9.0+1
  responsive_grid: ^2.0.0
  universal_html: ^2.0.8
  universal_ui: ^0.0.8
  flutter_launcher_icons: ^0.9.2
  favicon: ^1.0.15
  auto_size_text: ^3.0.0
  syncfusion_flutter_calendar: ^19.3.56
  syncfusion_localizations: ^19.3.56
  drag_and_drop_lists: ^0.3.2+2
  flutter_colorpicker: ^0.6.1
  external_path: ^1.0.1
  flutter_local_notifications: ^9.2.0
  flutter_native_timezone: ^2.0.0

dependency_overrides:
  flutter_colorpicker: ^0.6.0

dev_dependencies:
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  android: true
  ios: true 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: BubbleBee
      fonts:
        - asset: fonts/BubbleBee.ttf

    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf

    - family: Dancing
      fonts:
        - asset: fonts/DancingScript-Medium.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat.ttf

    - family: Montserrat-Medium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
  
    - family: Delberg
      fonts:
        - asset: fonts/Delberg.ttf

    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

    - family: Quaylike
      fonts:
        - asset: fonts/Quaylike.ttf
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:

  color: "#FFFFFF"
  image: assets/new_logo.png